#pragma once

#define FPS 60

#define BOARD_WIDTH 28
#define BOARD_HEIGHT 22
#define FBOARD_WIDTH (double)BOARD_WIDTH
#define FBOARD_HEIGHT (double)BOARD_HEIGHT

#define SQUARED_TOWER_RADIUS 25
#define SQUARED_PYRO_RADIUS 4
#define SQUARED_VAPORIZATION_RADIUS 12.25 // 3.5^2 
#define DAMAGE_FACTOR 100
#define TIME_BETWEEN_WAVES 35000
#define HEALTH_CONSTANT 500
#define SHOT_SPEED 3. / (FPS)
#define SHOT_INTERVAL 500

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
